# Site settings
title: S. Rashid Munir
email: smunir1@binghamton.edu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://srmunir.github.io/" # the base hostname & protocol for your site
#twitter_username: PeeDeeZee8
#github_username:  pdz8

# Build settings
markdown: kramdown

# pdz8 settings
exclude: [
  sandbox/,
  website.*,
  ]
permalink: /posts/:title
enable_disqus: false
enable_social: false
